using System.Reflection;


//[assembly: AssemblyConfiguration("{configuration}")]
[assembly: AssemblyConfiguration("Debug")] // Generated by AssemblyInfoRewriter
//[assembly: AssemblyCompany("{company}")]
[assembly: AssemblyCompany("Alvarez & Marsal")] // Generated by AssemblyInfoRewriter
//[assembly: AssemblyCopyright("Copyright © {company} {yyyy}")]
[assembly: AssemblyCopyright("Copyright © Alvarez & Marsal 2024")] // Generated by AssemblyInfoRewriter
[assembly: AssemblyProduct("PeerAMid")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

#pragma warning disable CS7035
//[assembly: AssemblyVersion("{majorVersionNumber}.{minorVersionNumber}.{gy}.{gm}{gd}")]
[assembly: AssemblyVersion("1.0.1.808")] // Generated by AssemblyInfoRewriter
//[assembly: AssemblyFileVersion("{gy}.{gm}.{gd}.{gitrevnum}")] // {gitrev}
[assembly: AssemblyFileVersion("1.0.1.808/1510")] // Generated by AssemblyInfoRewriter
//[assembly: AssemblyInformationalVersion("{majorVersionNumber}.{minorVersionNumber}.{gy}.{gm}{gd}")]
[assembly: AssemblyInformationalVersion("1.0.1.808/1510")] // Generated by AssemblyInfoRewriter
