using System.Reflection;


//[assembly: AssemblyConfiguration("{configuration}")]
[assembly: AssemblyConfiguration("Debug")] // Generated by AssemblyInfoRewriter
//[assembly: AssemblyCompany("{company}")]
[assembly: AssemblyCompany("Alvarez & Marsal")] // Generated by AssemblyInfoRewriter
//[assembly: AssemblyCopyright("Copyright © {company} {year}")]
[assembly: AssemblyCopyright("Copyright © Alvarez & Marsal 2024")] // Generated by AssemblyInfoRewriter
[assembly: AssemblyProduct("PeerAMid")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

#pragma warning disable CS7035
//[assembly: AssemblyVersion("{majorVersionNumber}.{minorVersionNumber}.{build}.{mmdd}")]
[assembly: AssemblyVersion("1.0.1.814")] // Generated by AssemblyInfoRewriter
//[assembly: AssemblyFileVersion("{majorVersionNumber}.{minorVersionNumber}.{build}.{mmdd}/{hhmm}")]
[assembly: AssemblyFileVersion("1.0.1.814/1619")] // Generated by AssemblyInfoRewriter
//[assembly: AssemblyInformationalVersion("{majorVersionNumber}.{minorVersionNumber}.{build}.{mmdd}/{hhmm}")]
[assembly: AssemblyInformationalVersion("1.0.1.814/1619")] // Generated by AssemblyInfoRewriter
